'''
Highly divisible triangular number
   
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''
import math

def triangleNumber(n):
    sum = 0
    for i in range(1, n + 1):
        sum += i
    return sum

def nFactors(num):
    if num == 1:
        return 1
    
    count = 2
    limit = int(math.ceil(num / 2))
    i = 2
    while i < limit:
        if num % i == 0:
            count += 2
            limit = int(math.ceil(num / i))
        i += 1

    return count

max = 0
n = 1
while max < 501:
    tNum = triangleNumber(n)
    nextValueNFactors = nFactors(tNum)
    if nextValueNFactors > max:
        max = nextValueNFactors
    n += 1

print(f'{tNum} is the {n}th triangular number and the first to have over 500 factors.')
print(f'It has {nextValueNFactors} factors.')